server:
  port: 9999
  servlet:
      context-path: /demo
spring:
    http:
      encoding:
        force: true
        charset: UTF-8
    application:
        name: spring-boot-web-socket
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html